### PR TITLE
[DO NOT MERGE] CBCC - User Stories

### PR DESCRIPTION
**Pull request by huyenltnguyen**
@artoodeeto I don't see where we can have a tracker to list out all the user stories of this app, so I created this PR. I had to make a stupid change in order to bypass Git's diffing 😄 Don't merge this PR.

We will just discuss either here or via Gitter, then edit this post to add a user story below.

# User Stories:
- [ ] As a user, I can select my city and see it fill in the blank in the paragraph.
- [ ] As a user, I can select my income and see it fill in the blank in the paragraph.
- [ ] As a user, I can...

### CODE REVIEW

**Comment by artoodeeto** [comment]
@huyenltnguyen  ohhh. okies. no problem. we can discuss it here if you want.

**Comment by huyenltnguyen** [comment]
@artoodeeto Yeah I prefer using GitHub to keep track of the discussion. Other chatting can go to Gitter.

I took a look at the jQuery and guess what, 80% of it is D3.js. I'm not familiar with it and I'm wondering if we just keep going or we should pass it to someone else 😟.

I managed to get the CBCC app working on my pc, I will upload it to codepen so you can play with it, too.

And I just realized that I made some styling mistake with the buttons. They should have a white background with a green border. I'm on night mode on FCC so the colors are different, and I mistakenly set the colors I saw (in night mode) to the buttons on day mode. I will create a PR for this.

**Comment by artoodeeto** [comment]
haahahha. i havent paid attention in your grammar as my grammar is worst. yea they used d3. i haven't used d3. we could learn it for sure but it will take time. maybe not right now. what do you think we could do?

**Comment by artoodeeto** [comment]
@huyenltnguyen yes the live cbcc isnt working and i couldn't understand the logic. is there a way that we could ask someone? maybe the dude who opened this?

**Comment by huyenltnguyen** [comment]
@artoodeeto You meant Bouncey? I don't think he knows the app that well. We have the author Twitter if we want to reach out. I don't use Twitter, so maybe we will need to ask Bouncey to be the middle man.

Have you try the app on my codepen? I extracted the app from the FCC codebase, then did some tweaking to get it to work. I didn't do anything complicated. It just the app doesn't or fails to load jQuery and d3, so I fixed it.

The first thing I will do is to update our progress in the issue thread and ask for some guidance on the d3. I would like to give it a try for a day to see if I could finish it, but I'm not sure exactly when I'm able to.

For now, I would suggest that both of us try decrypting the jQuery file. If there is a part that we figure out, we will write comments directly in that file to explain the code, then commit and push it here, just like how we have done with the `feat/` branch. I will create a separate branch for it, obviously. This way, if we decide to pass it to someone else, it will be very helpful to them.

What do you think?

**Comment by artoodeeto** [comment]
@huyenltnguyen yes ive check the codepen looks good. for the jquery thats a good idea. i will get a portion. lets say a function and then try to understand it and explain it to you. maybe just push it here. if you could ask bouncey about the the logic and maybe the formula we dont have to contact the original maker.

**Comment by huyenltnguyen** [comment]
Hi @artoodeeto, now that we have added new lines to the jquery file, I'm wondering we should just use those code blocks as tasks.

Could you tell me which part you have been working on and which part I can start? No rush, btw, I just wanted to know so that we don't overlap each other.

**Comment by huyenltnguyen** [comment]
Hi @artoodeeto, I'm starting to get back to this now after a long delay. I will self-merge my PRs (starts from #14) but please note that you can always revert the changes if you disagree. So, take a look when you have a chance. Thanks a lot and I hope things have been going well with your projects.

**Comment by artoodeeto** [comment]
@huyenltnguyen just read this right now. 6 days ago been a long time. if you still need help can you update me?

**Pull request closed without merging**
