### PR TITLE
Feat/cbcc notes2

### PR DESCRIPTION
**Pull request by artoodeeto**
#### Pre-Submission Checklist

- [ ] Your pull request targets the `staging` branch of freeCodeCamp.
- [ x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [ x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ x] Tested changes locally.
- [ ] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #XXXXX

#### Description

@huyenltnguyen hello again. hahahah. i fixed my work. i think this is good now. its up to you if you want to merge it. but basically i just copy paste the notes. i also created a fn instead of putting the whole think in the `render()` just for readability but if its not the standard you can edit it or i could :) thanks again. i didn't do anything here. hahaha. its all you. :)

### CODE REVIEW

**Comment by huyenltnguyen** [comment]
@artoodeeto Thanks for the great work! I like the way you format the `cities` and `incomes` arrays. It's way easier to read 👍 I haven't pulled it down yet. I'm just looking at it while finishing my breakfast 😄 Will try my best.

Don't say you didn't do anything. While I'm able to do it all (and I'm sure so can you), it's great to have someone review my code and bounce ideas off. As I mentioned earlier, this is the first time I have ever used Git to collaborate, so you're helping me learn, too. Don't just look at the surface, I have learned a lot from this, and you have played a big part in it.

---
Oh hey, I just noticed that your PR is pointing to the `next` branch. It should be `feat/coding-bootcamp-cost-calculator` instead? I think that's what happened to your earlier PRs too. I think you can change the `base` from `next` to `feat/coding-bootcamp-cost-calculator` right here on Github by clicking the Edit button.

**Comment by artoodeeto** [comment]
@huyenltnguyen  OMG!!!! im so sorry!!! I got up from my bed and started coding. my bad. im sorry but i change the base again. my bad. i was lost. thank you thank you again. Everything here is all you. im just a props. hahaha. im sorry if im on and off on this work i had to make a chat feature for our group project and i dont feel good this pass few days. well thank you so much again :)

**Comment by artoodeeto** [comment]
@huyenltnguyen hello. can i merge this? haha.

**Comment by huyenltnguyen** [comment]
@artoodeeto I'm testing it right now. Will need to make some changes though.

**Comment by artoodeeto** [comment]
@huyenltnguyen ok. no worries. 👍 thanks

**Comment by huyenltnguyen** [comment]
@artoodeeto I'm done with reviewing this PR.

I decided to just bring the whole notes into the `render()` instead of creating it using a method because they will just take up as much lines anyway.

Some other changes I made are in regards to style consistency and they are very minor.

Thanks for the help! I'm merging it now.

**Comment by artoodeeto** [comment]
@huyenltnguyen thanks much. :) no problem.

**Pull request merged**
